import Head from "next/head";

const CHead = () => {
  return (
    <div>
      <Head>
        <title>Rising Talent | An NFT Marketplace</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    </div>
  );
};

export default CHead;
